### ISSUE TITLE
Title - Cümle değişimi

### ISSUE THREAD

**Issue by metekoraygergin** [node101-io/istanbulblockchainevents#1]
Alper selam,

Istanbul Blockchain Events is a public good project that allows you to find all crypto events held in Istanbul. This project is fully funded by node101.

şeklinde bu bölümü yeniden yazalım lütfen.

![image](https://github.com/node101-io/istanbulblockchainevents/assets/132212778/8bbfd97c-f1c9-453a-9e23-c75375b4e703)

**Comment by alpersam** [comment]
Fixed
