### ISSUE TITLE
Sağ sol çatışması

### ISSUE THREAD

**Issue by metekoraygergin** [node101-io/istanbulblockchainevents#11]
![image](https://github.com/node101-io/istanbulblockchainevents/assets/132212778/65e06121-8991-42f6-81dd-6e1c75c8bb6f)

Alper selam,

Sağ cenahtaki yazıları sol cenaha, sol cenahtaki yazıları da sağ cenaha alırsak daha rahat okunur. Böyle Turkish Lira -> Currency oluyo, Currency -> Turkish Lira

**Comment by alpersam** [comment]
Aslinda wireframe'e bakinca sagdaki yazilarin soldakilerin kategorisi olmadiklarini, farkli linkler olduklarini fark ettim. Istersen wireframe'deki gibi tutup dizayni linkleri ekleyebilirim

![image](https://github.com/node101-io/istanbulblockchainevents/assets/39453669/2e5d7a4d-06e7-4bca-8fa9-9b7a103a677a)
