### ISSUE TITLE
Type - Main & Side event ve diğer Type filterlerinin arasındaki farkların dayanaklarının ve bu ayrımın event satırlarına etkisinin netleştirilmesi

### ISSUE THREAD

**Issue by metekoraygergin** [node101-io/istanbulblockchainevents#2]
![image](https://github.com/node101-io/istanbulblockchainevents/assets/132212778/d9389aff-45d7-4583-9db8-3aa7a0c1d7d7)

Alper selam,

sanırım bu nokta tam netleştirilmedi seninle, event isimlerinin 3 farklı rengi var bu renkler main event, side event ve party typelarına ayrılmış durumda sadece. Main event ve side eventlerin renkleri olan mavi ve yeşil onların main mi side mı olduğunu gösteriyor, ve tüm eventlere uygulanıyor. Yalnızca party etkinliklerinin (sırf daha ilgi çekici olsun diye) rengi turuncudur ve main ya da side olup olmadığından bağımsız olarak uygulanır. 

Dolayısıyla, zaten main mi side mı olduğunu, etkinliğim isminin renginden belli ediyoruz. Dolayısıyla eventlerin listelendiği satırların en sağında bulunan type sütününda main mi side mı olduğu yazılmamalı. Orada mesela main bir eventin conference mı hackathon mu olduğu yazılmalı, zaten main olduğu etkinliğin isminin renginden belli oluyor.

Fakat, party olan bir etkinliğin ismi turuncu renkte olduğu halde, type sutununda party yazmalıdır.

**Comment by alpersam** [comment]
Tamamdir, gerekli duzeltmeyi yaptim. Figma dosyasindaki layout'u direk gecirmistim, o yuzden type'i Main/side event yapmistim. Ancak dogru anladiysam o zaman soldaki checkbox'larda da main-side event boxlari olmayacak degil mi?
