### ISSUE TITLE
Landing yazı düzenlemeleri

### ISSUE THREAD

**Issue by lalenas** [node101-io/istanbulblockchainevents#5]
![image](https://github.com/node101-io/istanbulblockchainevents/assets/138670978/33de30a5-3657-4d4b-838f-194f820701ed)
tasarımda başlık daha uzun ve altında by node101 yazıyor ve link seklinde olan node101 yazısı renkleri farklı olmuş bu şekilde düzenleme yapabilir miyiz

**Comment by alpersam** [comment]
Fixed
