### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lalenas** [node101-io/istanbulblockchainevents#8]
![image](https://github.com/node101-io/istanbulblockchainevents/assets/138670978/17014b4c-1143-4725-b849-ab7d49348100)
Tasarımdaki gibi güncellenebilir mi

**Comment by alpersam** [comment]
Su an zaten bu dizaynda 1200px'e kadar. 1000px'e kadar boyle tutabilirim:
![image](https://github.com/node101-io/istanbulblockchainevents/assets/39453669/e42b4f85-5aee-4176-8f73-40b11a5295e8)
Yoksa 1200px'den sonra nasil bi gorunume burunsun asagisi, sosyal medya ikonlari yaziya girmesin diye

**Comment by lalenas** [comment]
yazılardan bahsediyordum benim hatam about us kaldırılmalı about istanbul yerine istanbul guide getirilmeli

**Comment by alpersam** [comment]
Aaa tamam, duzelttim
