### ISSUE TITLE
Istanbul Guide Sayfasının Linklerinin Linklenmesi 

### ISSUE THREAD

**Issue by metekoraygergin** [node101-io/istanbulblockchainevents#9]
Selam Alper,

Istanbul Guide sayfası bildiğin üzere İstanbulu anlatan bir sayfa. Bu anlatı sırasında birçok link de veriyoruz diğer sayfalara gitmeleri için. Ben bu linkleri, wireframe tasarımlarında yorum olarak bırakmıştım. Şimdi sana wireframe figmasının linkini veriyorum, bu linke girerek. **"Istanbul Blockchain Events - Istanbul Guide"** başlığının altındaki wireframe tasarımlarını inceleyerek o yorumlara ulaşabilirsin. linklemen gereken tüm linkleri yorum olarak oraya bıraktım. 
https://www.figma.com/file/wlySrb903vulV8MHP0mV7o/Wireframes?type=design&node-id=0%3A1&mode=design&t=QRKneZMREuJuR2tL-1

**Comment by metekoraygergin** [comment]
![image](https://github.com/node101-io/istanbulblockchainevents/assets/132212778/fe09e8f8-5c63-4a81-b580-4e7c84403745)

buradaki harita da aslında bi google haritası, bunu da gömmemiz lazım siteye, linki var haritanın wireframede

**Comment by alpersam** [comment]
Selam, sence hangisi daha iyi linki vurgulamak icin?
![image](https://github.com/node101-io/istanbulblockchainevents/assets/39453669/593157a2-4c82-4ef9-b642-a33ad0e815d9)
![image](https://github.com/node101-io/istanbulblockchainevents/assets/39453669/ae286cbe-2e09-431d-82fb-40fc807e3908)

Ya direk geri kalan textin aynisiyla mi birakayim?

**Comment by alpersam** [comment]
Fixed
